#!/bin/sh

# This script generates reference.py from the README.md file.

cat <<EOF > reference.py
# Reference implementation of BIP DKG. This file is automatically generated by
# reference_py_gen.sh.

from secp256k1 import n as GROUP_ORDER, Point, G, point_add, point_mul
from typing import Tuple, List, Optional
EOF

# Define markdown section start string and end string
START_STRING="### Verifiable Secret Sharing (VSS)"
END_STRING="## DKG Protocols"

# Extract lines between START_STRING and END_STRING from ../README.md
sed -n "/$START_STRING/,/$END_STRING/p" ../README.md | grep "\`\`\`python" -A 100000 | grep "\`\`\`"  -B 100000 | sed '1d;$d' >> reference.py