#!/bin/sh

# This script generates reference.py from the README.md file.

cd "$(dirname "$0")"

cat <<EOF > reference.py
# Reference implementation of BIP DKG. This file is automatically generated by
# reference_py_gen.sh.

from crypto_bip340 import n as GROUP_ORDER, G, point_mul, tagged_hash, int_from_bytes, bytes_from_int, schnorr_sign, schnorr_verify
from crypto_extra import pubkey_gen_plain, point_add_multi, cpoint, xbytes, cbytes, cbytes_ext
from network import SignerChannel, CoordinatorChannels
from typing import Tuple, List, Optional, Any, Union, Literal
# Another type
from crypto_bip340 import Point
from util import InvalidContributionError, InvalidBackupError, DeserializationError, VSSVerifyError, DuplicateHostpubkeyError
EOF

awk '/### Assumed Functions/,/## Background on Equality Check Protocols/ {
    if ($0 ~ /^```python$/) {
        in_python_block = 1;
        print "";
        next;
    }
    if (in_python_block && $0 ~ /^```$/) {
        in_python_block = 0;
    }
    if (in_python_block) {
        print $0;
    }
}' ../README.md >> reference.py
